// Human- *and* search-engine-friendly text for each generated tool.
//
// Mealie's OpenAPI spec is generated by FastAPI, so most operations carry only
// a two-word title-cased summary ("Patch One", "Get All") and frequently no
// description at all. Passed straight through, that leaves tools whose entire
// description is `Patch One\n[PATCH /api/recipes/{slug}]` — nothing for a tool
// search index (or a model skimming the list) to match "update recipe" against.
// The helpers here reconstruct the missing vocabulary from the parts of the
// spec that *are* meaningful: the tag, the path and the HTTP method.

import type { HttpMethod, OpenApiOperation } from "./openapi-types.js";

/** Hard ceiling on a generated description, matching the MCP tool-description budget. */
const MAX_DESCRIPTION = 2000;

/** Path words Mealie writes as one token but readers (and search) split. */
const COMPOUND_WORDS: Record<string, string> = {
  mealplan: "meal plan",
  mealplans: "meal plans",
  mealplanner: "meal planner",
};

/** Segments too generic to name a resource on their own; they borrow the segment before them. */
const WEAK_SEGMENTS = new Set(["item", "items", "one", "all", "self", "current"]);

/**
 * Trailing segments that name the *action* rather than the resource
 * (`/recipes/{slug}/duplicate`), mapped to the imperative verb they imply. The
 * resource is whatever precedes them.
 */
const ACTION_SEGMENTS: Record<string, string> = {
  check: "Check",
  clean: "Clean",
  create: "Create",
  "create bulk": "Bulk create",
  delete: "Delete",
  download: "Download",
  duplicate: "Duplicate",
  export: "Export",
  exports: "Export",
  import: "Import",
  merge: "Merge",
  parse: "Parse",
  purge: "Purge",
  refresh: "Refresh",
  rerun: "Re-run",
  restore: "Restore",
  seed: "Seed",
  test: "Test",
  "test scrape url": "Test",
  trigger: "Trigger",
  unlock: "Unlock",
  update: "Update",
  upload: "Upload",
};

/** Trailing segments that name a lookup key or representation, not a resource or an action. */
const NOISE_SEGMENTS = new Set([
  "bulk",
  "bulk actions",
  "callback",
  "empty",
  "html or json",
  "slug",
  "stream",
  "temp",
  "today",
  "url",
  "zip",
]);

interface Action {
  /** Verb phrase used in the generated sentence. */
  verb: string;
  /** Alternative phrasings a user might search for. */
  synonyms: string[];
}

const METHOD_ACTIONS: Record<string, Action> = {
  "get:collection": { verb: "List", synonyms: ["list", "get", "search", "find", "browse", "fetch", "read"] },
  "get:item": { verb: "Get", synonyms: ["get", "fetch", "read", "retrieve", "view", "show"] },
  post: { verb: "Create", synonyms: ["create", "add", "new", "make", "write"] },
  put: { verb: "Replace (full update)", synonyms: ["update", "replace", "edit", "modify", "save", "write"] },
  patch: { verb: "Partially update", synonyms: ["patch", "update", "edit", "modify", "change", "write"] },
  delete: { verb: "Delete", synonyms: ["delete", "remove", "destroy", "write"] },
};

/** Crude English singularisation — good enough for REST path segments. */
export function singularize(word: string): string {
  if (/ies$/.test(word) && word.length > 4) return `${word.slice(0, -3)}y`;
  if (/(s|x|z|ch|sh)es$/.test(word)) return word.slice(0, -2);
  if (/ss$/.test(word) || !/s$/.test(word) || word.length <= 3) return word;
  return word.slice(0, -1);
}

function expandCompounds(phrase: string): string {
  return phrase
    .split(" ")
    .map((w) => COMPOUND_WORDS[w] ?? w)
    .join(" ");
}

/** Path segments that name something, dashes and dots normalised to spaces. */
export function pathSegments(path: string): string[] {
  return path
    .split("/")
    .filter((s) => s.length > 0 && s !== "api" && !s.startsWith("{"))
    .map((s) => expandCompounds(s.replace(/[-_.]+/g, " ").toLowerCase()));
}

export interface Resource {
  /** Plural noun phrase, e.g. "meal plans". */
  plural: string;
  /** Singular noun phrase, e.g. "meal plan". */
  singular: string;
  /** Whether the two differ, i.e. the path segment really did read as a plural. */
  isPlural: boolean;
  /** Imperative verb implied by a trailing action segment, if the path had one. */
  actionVerb?: string;
}

/**
 * The resource an operation acts on, derived from the path — Mealie's paths are
 * consistently resource-shaped, where its summaries are not. Trailing action and
 * lookup-key segments are skipped (`/recipes/create/zip` is about recipes), and
 * a trailing weak segment borrows the one before it, so
 * `/shopping/lists/{id}/items` yields "list item" rather than "item".
 */
export function resourceNoun(path: string): Resource {
  const segments = pathSegments(path);
  let index = segments.length - 1;
  let actionVerb: string | undefined;
  while (index > 0) {
    const segment = segments[index]!;
    if (ACTION_SEGMENTS[segment]) actionVerb = ACTION_SEGMENTS[segment];
    else if (!NOISE_SEGMENTS.has(segment)) break;
    index--;
  }

  const last = segments[index];
  if (!last) return { plural: "records", singular: "record", isPlural: true };

  const previous = segments[index - 1];
  const plural = WEAK_SEGMENTS.has(last) && previous ? `${singularize(previous)} ${last}` : last;
  const words = plural.split(" ");
  const singular = [...words.slice(0, -1), singularize(words[words.length - 1]!)].join(" ");
  return { plural, singular, isPlural: singular !== plural, actionVerb };
}

/** Does the path address a single record (ends in a path parameter)? */
function isItemScoped(path: string): boolean {
  const segments = path.split("/").filter((s) => s.length > 0);
  return Boolean(segments[segments.length - 1]?.startsWith("{"));
}

/**
 * A GET only reads a collection when the path addresses no single record *and*
 * the resource reads as a plural — `/api/app/about` is a singleton, not a list.
 */
function listsMany(method: HttpMethod, path: string, resource: Resource): boolean {
  return method === "get" && !isItemScoped(path) && resource.isPlural;
}

function actionFor(method: HttpMethod, path: string, resource: Resource): Action {
  if (method !== "get") return METHOD_ACTIONS[method]!;
  return METHOD_ACTIONS[listsMany(method, path, resource) ? "get:collection" : "get:item"]!;
}

/** Flatten a tag ("Recipe: CRUD") into plain searchable words ("recipe crud"). */
function tagWords(tag: string): string {
  return expandCompounds(tag.replace(/[:_-]+/g, " ").replace(/\s+/g, " ").trim().toLowerCase());
}

function addKeyword(seen: Set<string>, out: string[], value: string): void {
  const keyword = value.trim().toLowerCase();
  if (keyword.length === 0 || seen.has(keyword)) return;
  seen.add(keyword);
  out.push(keyword);
}

/**
 * The phrases someone is most likely to type when looking for this tool: its own
 * name, its category, the resource it acts on and every verb that means the same
 * thing as its HTTP method.
 */
export function buildKeywords(
  op: OpenApiOperation,
  path: string,
  method: HttpMethod,
  name: string,
  category: string,
): string[] {
  const seen = new Set<string>();
  const keywords: string[] = [];
  const resource = resourceNoun(path);
  const action = actionFor(method, path, resource);
  const many = listsMany(method, path, resource);

  addKeyword(seen, keywords, name);
  addKeyword(seen, keywords, name.replace(/_/g, " "));
  if (resource.actionVerb) addKeyword(seen, keywords, `${resource.actionVerb} ${resource.singular}`);
  for (const verb of action.synonyms) {
    addKeyword(seen, keywords, `${verb} ${resource.singular}`);
    if (many) addKeyword(seen, keywords, `${verb} ${resource.plural}`);
  }
  addKeyword(seen, keywords, resource.singular);
  addKeyword(seen, keywords, resource.plural);
  for (const tag of op.tags ?? []) addKeyword(seen, keywords, tagWords(tag));
  addKeyword(seen, keywords, category.replace(/_/g, " "));
  for (const segment of pathSegments(path)) addKeyword(seen, keywords, segment);
  for (const verb of action.synonyms) addKeyword(seen, keywords, verb);
  addKeyword(seen, keywords, method);
  addKeyword(seen, keywords, method === "get" ? "read-only" : "write");
  addKeyword(seen, keywords, "mealie");

  return keywords;
}

/**
 * A one-line summary that always names the resource and the action, even when
 * the spec only offered "Patch One".
 */
export function buildHeadline(op: OpenApiOperation, path: string, method: HttpMethod): string {
  const resource = resourceNoun(path);
  const verb = resource.actionVerb ?? actionFor(method, path, resource).verb;
  const noun = listsMany(method, path, resource) ? resource.plural : resource.singular;

  const tag = op.tags?.[0];
  const parts: string[] = [];
  if (op.summary) parts.push(tag ? `${op.summary} — ${tag}.` : `${op.summary}.`);
  else if (tag) parts.push(`${tag}.`);
  parts.push(`${verb} ${noun}.`);
  return parts.join(" ");
}

/**
 * Build the full tool description: headline, the literal method and path (which
 * clients do match on), the spec's own prose, then a keyword line so a search
 * for "update recipe" reaches `recipe_crud_patch_one`.
 */
export function buildDescription(
  op: OpenApiOperation,
  path: string,
  method: HttpMethod,
  name: string,
  category: string,
): string {
  const headline = buildHeadline(op, path, method);
  const lead = op.deprecated ? `(DEPRECATED) ${headline}` : headline;
  const route = `[${method.toUpperCase()} ${path}]`;
  const keywords = `Keywords: ${buildKeywords(op, path, method, name, category).join(", ")}.`;

  const fixed = [lead, route, keywords];
  const detail = op.description?.trim();
  if (!detail || detail === op.summary) return fixed.join("\n");

  // Only the spec's free-form prose is allowed to overflow, so the keyword line
  // (the part a search index needs most) is never the thing that gets cut.
  let fixedLength = 0;
  for (let i = 0; i < fixed.length; i++) {
    fixedLength += fixed[i].length + 1;
  }
  const budget = MAX_DESCRIPTION - fixedLength;
  if (budget <= 0) return fixed.join("\n");
  const trimmed = detail.length > budget ? `${detail.slice(0, Math.max(0, budget - 3))}...` : detail;
  return [lead, route, trimmed, keywords].join("\n");
}
